version: '3'
services:
  gcode-tupi-core:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NODE_ENV=${APP_ENV}
    image: gcode-tupi-core:latest
    container_name: gcode-tupi-core
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ../:/usr/src/app
      - ../.docker/.env:/.env
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${APP_ENV}
